# Generated by Django 5.2.6 on 2025-10-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_invoice_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='dimensions',
            field=models.CharField(blank=True, choices=[('normal', '10x15'), ('medium', '13x18'), ('large', '20x30')], max_length=50, null=True),
        ),
    ]
