# Generated by Django 5.2.6 on 2026-01-07 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderitem_dimensions'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='confirmation_mail_sent_at',
            field=models.DateTimeField(blank=True, help_text='When the order confirmation email was successfully sent', null=True),
        ),
    ]
